export const projects = [
  {
  title: 'WordPress Marketing Services/Ecommerce',
    description: "online marketplace for audio, lighting, and video equipment rentals and sales. The website has a modern and visually appealing design, with high-quality product images and detailed descriptions.PHP: WordPress is built using the PHP programming language, and the website uses Wordpress  to generate dynamic content and MySQL to interact with the database.",
    image: '/images/old-gearsource.jpg',
    tags: ['WordPress / WooCommerce', 'PHP', 'JavaScript'],
    source: 'https://gitlab.com/siono_teamdev/wordpress/gearsource',
    visit: 'https://gearsource.wpengine.com/',
    id: 0,
  },
  {
    title: 'WordPress Booking Boat Platform',
    description: "The front-end of the website features a responsive design, allowing for a seamless user experience across different devices. Users can browse available boats by location, size, and type, and select their preferred rental dates using an integrated calendar. The website also offers a blog section where users can read articles related to boating, fishing, and other water-based activities.",
      image: '/images/wordpress.jpg',
      tags: ['MySQL', 'WordPress', 'PHP', 'JavaScript'],
    source: '#',
    visit: 'https://onthewaterboatrental.com/',
    id: 1,
  },
  {
    title: 'Big ECommerce Multivendor',
    description:"big-ecommerce, development of custom integrations in php and SQL(wordpress), modules for marketing and sales operations, maintenance of code and project repositories. Subsequent replatforming executing various backend and frontend tasks.",
    image: '/images/gearproject.jpg',
    tags: ['React', 'JavaScript','Builder.io'],
    source: 'https://github.com/HMQM-0/gearsource-backup',
    visit: 'https://gearsource.com/',
    id: 2,
  },
  {
    title: 'Ecommerce with NextJS & GraphQL',
    description: "The website's core functionality is centered around a pet screening process that involves the submission of an online pet application, verification of pet ownership and veterinary records, and the assessment of a pet's behavior and suitability for a particular rental property.",
      image: '/images/petscreening.jpg',
      tags: ['NextJS', 'GraphQL','Builder.io'],
    source: 'https://github.com/HMQM-0/Petscreenning-project-backup',
    visit: 'https://petscreening.nauticalcommerce.com/',
    id: 3,
  },
  {
    title: 'WordPress Marketing Services/Ecommerce',
    description: "Personal website for a martial arts instructor named Carina Salvó. The website is builded using the WordPress content management system (CMS). The website utilizes a responsive design, which means it adjusts to fit various screen sizes, including desktop, tablet, and mobile devices. The website also incorporates modern design elements, including a large hero image, parallax scrolling effects, and a minimalist color scheme.",
    image: '/images/kenpo-project.jpg',
    tags: ['WordPress / WooCommerce', 'PHP', 'JavaScript'],
    source: 'https://github.com/HMQM-0/AKI-Website',
    visit: 'https://carinasalvokenpo.com/',
    id: 4,
  },
];

